### ISSUE TITLE
Mild CSS issue

### ISSUE THREAD

**Issue by agm1984** [jbitton/neo4j-graph-renderer#1]
Greetings, this Neo4j Component is literally amazing. Thanks for producing it.

I just installed it, and had a couple trouble spots I think we can fix, and then once I got the right config, boom, it works MINT.

First, I installed it and ran it as per your docs, but I didn't have style-loader or css-loader installed in webpack, so issue #1, I think you should mention that in the docs. It threw some errors about CSS in the console that were fairly easy to trace. I am just using one custom CSS file loaded in my index.html along with bootstrap, so this is why I saw this issue. It's for a load testing app using which, we have need to see the nodes we are creating to ensure they were created properly.

Here is the Webpack config I used to get it working:

```
{
    test: /\.css$/,
    use: ['style-loader', 'css-loader']
}
```

Second, I am still having a bonus issue related to CSS, and I'm not sure what exactly. I haven't looked too close yet. It's throwing this in the console:

```
GET http://localhost:1337/styles/neod3.css 404 (Not Found)
```

I don't know the nature of that file or `~/styles` so maybe you could mention that in the docs also.

Third, It's been a while since I used the Neo4j REST endpoint, so I forgot the syntax. Maybe you could include an example config. It would have saved me like 5 mins and 3 iterations of running the code before I remembered I needed http:// and :7474 in the URI.

Something like:
```
Props you must provide:
url: the url required to access your neo4j db (eg: url="http://localhost:7474")
```

That said, seriously excellent work, I imagine I will use this library religiously now and may even contribute to it if you like. Feel free to send me a note ever if you need some help or thinking of abandoning the project. I scoured the internet for like half a day plus weeks of occasional searching, and this is the best package, comically fast to get setup too.

**Comment by jbitton** [comment]
Hello Adam!

Wow, thank you so much for all of your praise -- it means a lot! Thank you for mentioning these issues -- I will fix it right now!

Also -- so sorry for only getting back to you now.

Joanna

**Comment by jbitton** [comment]
@agm1984 I've created a PR for these issues, but there are no real "collaborators" besides me for this project, so it'd be much appreciated if you can look it over and make sure it resolves all your issues. I'll update the npm package and master once I have your approval.

**Comment by jbitton** [comment]
I've decided to merge the PR to prevent other individuals from having issues. Please open another issue if your problems persist.
